# Generated by Django 4.1.3 on 2023-11-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_outlets'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlets',
            name='outlet_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outlets',
            name='outlet_logo',
            field=models.ImageField(blank=True, null=True, upload_to='pics/outlet_logo'),
        ),
        migrations.AddField(
            model_name='outlets',
            name='staff',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
