# Generated by Django 4.1.3 on 2023-11-13 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_outlets_outlet_description_outlets_outlet_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlets',
            name='outlet',
        ),
        migrations.AddField(
            model_name='outlets',
            name='outlet',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
