# Generated by Django 4.1.3 on 2023-11-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_outlets_outlet_outlets_outlet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlets',
            name='outlet',
        ),
        migrations.AddField(
            model_name='customuser',
            name='outlet',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.outlets'),
        ),
    ]
