# Generated by Django 4.1.3 on 2023-11-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlets',
            name='name',
            field=models.CharField(default='first bukkof gas', max_length=50),
        ),
    ]
