# Generated by Django 4.1.3 on 2023-11-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_outlets_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlets',
            name='name',
            field=models.CharField(default='Please enter your outlet name', max_length=50),
        ),
    ]
