# Generated by Django 4.2.4 on 2023-11-27 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_outlets_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('manager', 'manager'), ('supervisor', 'Manager'), ('staffs', 'staffs')], default='staffs', max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=600, verbose_name='Description')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
