# Generated by Django 4.2.4 on 2023-11-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_outletstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstaff',
            name='status',
            field=models.CharField(choices=[('manager', 'manager'), ('supervisor', 'supervisor'), ('staffs', 'staffs')], default='staffs', max_length=100),
        ),
    ]
