# Generated by Django 4.2.4 on 2023-11-27 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_outletstaff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstaff',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.outlets'),
        ),
    ]
