# Generated by Django 4.2.4 on 2023-12-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_outletstaff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Admin', 'Admin'), ('supervisor', 'supervisor')], default='attendant', max_length=100),
        ),
        migrations.AlterField(
            model_name='outletstaff',
            name='status',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Employee', 'Employee')], default='staff', max_length=100),
        ),
    ]
