# Generated by Django 4.2.4 on 2023-12-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_customuser_status_alter_outletstaff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletstaff',
            name='password',
            field=models.CharField(default='1111', max_length=128),
            preserve_default=False,
        ),
    ]
