# Generated by Django 4.2.4 on 2023-12-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_outletstaff_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletstaff',
            name='password',
        ),
    ]
