# Generated by Django 4.2.4 on 2023-12-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_outletstaff_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletstaff',
            name='unique_id',
            field=models.CharField(default=2, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
