# Generated by Django 4.2.4 on 2023-12-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_outletstaff_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstaff',
            name='unique_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
