# Generated by Django 4.2.4 on 2023-12-10 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_outletstaff_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletstafflogin',
            name='Employee_id',
        ),
    ]
