# Generated by Django 4.2.4 on 2023-12-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_outletstafflogin_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstafflogin',
            name='outlet_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.outletstaff'),
        ),
    ]
