# Generated by Django 4.2.4 on 2023-12-10 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_outletstafflogin_outlet_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstafflogin',
            name='outlet_staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.outletstaff'),
        ),
    ]
