# Generated by Django 4.2.4 on 2023-12-11 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_outletstafflogin_outlet_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletstaff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/staffs/profile_picture'),
        ),
        migrations.AddField(
            model_name='outletstafflogin',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
