# Generated by Django 4.2.4 on 2023-12-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_outletstaff_image_outletstafflogin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstaff',
            name='Employee_id',
            field=models.CharField(max_length=4),
        ),
    ]
