# Generated by Django 5.0.2 on 2024-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_remove_customuser_image_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstaff',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture_upload_path'),
        ),
    ]
