# Generated by Django 5.0.3 on 2024-05-15 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_outletstaff_email_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstafflogin',
            name='outlet_staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.outletstaff'),
        ),
    ]
