# Generated by Django 4.2.4 on 2023-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisto',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
