# Generated by Django 4.2.4 on 2023-11-24 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_outlets_name'),
        ('firstpos', '0002_productlisto_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.outlets'),
        ),
    ]
