# Generated by Django 4.2.4 on 2023-11-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstpos', '0003_productlist_outlet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='outlet',
        ),
    ]
