# Generated by Django 4.2.4 on 2023-12-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstpos', '0005_salesreceipt_attending_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreceipt',
            name='attending_employee',
        ),
    ]
