# Generated by Django 4.2.4 on 2023-12-26 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import firstpos.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstpos', '0006_remove_salesreceipt_attending_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_inventory', firstpos.fields.PositiveDecimalFromOneField(decimal_places=2, max_digits=10)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpos.productlisto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
