# Generated by Django 4.2.4 on 2023-12-26 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstpos', '0007_stockinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinventory',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpos.productlist'),
        ),
    ]
