# Generated by Django 4.2.4 on 2023-12-26 13:46

from django.db import migrations
import firstpos.fields


class Migration(migrations.Migration):

    dependencies = [
        ('firstpos', '0009_productlist_stock_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='stock_inventory',
            field=firstpos.fields.PositiveDecimalFromOneField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
