# Generated by Django 4.2.4 on 2023-12-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpos', '0011_alter_productlist_stock_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='stock_inventory',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=50, null=True),
        ),
    ]
