# Generated by Django 4.2.4 on 2024-01-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpos', '0012_alter_productlist_stock_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Amount_tenderd',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True),
        ),
    ]
