# Generated by Django 5.0.2 on 2024-02-17 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpos', '0013_alter_payment_amount_tenderd_alter_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesreceipt',
            old_name='payment',
            new_name='paymentT',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='products',
        ),
        migrations.AddField(
            model_name='payment',
            name='Payemntfor_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstpos.salesreceipt'),
        ),
    ]
