# Generated by Django 5.0.3 on 2024-04-19 16:19

import django.core.validators
import firstpos.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpos', '0014_rename_payment_salesreceipt_paymentt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Amount_tenderd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='stock_inventory',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='productlisto',
            name='Quantity',
            field=firstpos.fields.PositiveDecimalFromOneField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
